import type { Metadata } from "next";
import styles from "./page.module.css";

export const metadata: Metadata = {
  title: "Documentation | FDL",
  description: "A curated path through FDL concepts, examples, architecture, and contribution guidance.",
};

const repo = "https://github.com/pmcelhaney/FDL";

const sections = [
  {
    number: "01",
    title: "Start here",
    description: "Understand the product problem first, then see one definition drive input, validation, and output.",
    links: [
      { label: "Run the payment scenario", href: "/demo", detail: "Narrative walkthrough" },
      { label: "Read the project case study", href: "/case-study", detail: "Decisions and tradeoffs" },
      { label: "Install and run FDL", href: `${repo}#run-locally`, detail: "Fresh-clone path" },
    ],
  },
  {
    number: "02",
    title: "Core concepts",
    description: "The three model objects form a small vocabulary for reusable field and collection behavior.",
    links: [
      { label: "FieldType", href: `${repo}/blob/main/docs/field-type.md`, detail: "Immutable field definitions" },
      { label: "Record", href: `${repo}/blob/main/docs/record.md`, detail: "Values, events, and validation" },
      { label: "Recordset", href: `${repo}/blob/main/docs/recordset.md`, detail: "Fetching, sorting, filtering, paging" },
    ],
  },
  {
    number: "03",
    title: "Architecture",
    description: "Business rules, accessible component semantics, and visual presentation remain separate concerns.",
    links: [
      { label: "Design principles", href: `${repo}/blob/main/docs/design-principles.md`, detail: "The complete engineering guide" },
      { label: "Unified field component", href: `${repo}/blob/main/docs/adr/0002-use-one-field-custom-element.md`, detail: "ADR-0002" },
      { label: "Modifier retirement", href: `${repo}/blob/main/docs/adr/0001-retire-post-jack-henry-modifiers.md`, detail: "ADR-0001 and migration inventory" },
    ],
  },
  {
    number: "04",
    title: "Examples and reference",
    description: "Move from the coherent end-to-end story into focused examples and the complete support inventory.",
    links: [
      { label: "Modifier support matrix", href: "/reference", detail: "66 modifiers, candidly classified" },
      { label: "Lit form-control example", href: `${repo}/tree/main/examples/fdl-input`, detail: "Working form and table adapters" },
      { label: "Modifier catalog source", href: `${repo}/blob/main/examples/fdl-input/fdl-modifier-catalog.ts`, detail: "Focused behavior evidence" },
    ],
  },
  {
    number: "05",
    title: "API surface",
    description: "The curated guides are the entry point; declarations and source provide the exact current contract.",
    links: [
      { label: "Public exports", href: `${repo}/blob/main/index.d.ts`, detail: "Package declarations" },
      { label: "FieldType builder types", href: `${repo}/blob/main/types/field-type-builder.types.ts`, detail: "Modifier signatures" },
      { label: "FormElement adapter", href: `${repo}/blob/main/docs/form-element.md`, detail: "Lit integration contract" },
    ],
  },
  {
    number: "06",
    title: "Contribute and release",
    description: "Keep public behavior, declarations, tests, documentation, and examples aligned in every change.",
    links: [
      { label: "Contributor guide", href: `${repo}/blob/main/AGENTS.md`, detail: "Workflow and architecture rules" },
      { label: "Release process", href: `${repo}/blob/main/docs/releases.md`, detail: "SemVer and checklist" },
      { label: "Changelog", href: `${repo}/blob/main/CHANGELOG.md`, detail: "Unreleased work and baselines" },
    ],
  },
];

export default function DocsPage() {
  return (
    <main className={styles.page}>
      <header className={styles.hero}>
        <p className={styles.eyebrow}>Documentation gateway</p>
        <h1>Learn the model in the order you’ll use it.</h1>
        <p>
          FDL keeps field behavior in one declarative layer, then lets forms, tables, and output
          adapters interpret it. This is a curated map of the repository’s real documentation—not
          an autogenerated API that promises more than the code delivers.
        </p>
      </header>

      <section className={styles.quickstart} aria-labelledby="local-heading">
        <div>
          <p className={styles.kicker}>Fresh clone</p>
          <h2 id="local-heading">Run library and portfolio locally</h2>
          <p>Node 22 is the shared baseline because the portfolio requires Node 22.13 or newer.</p>
        </div>
        <div className={styles.commands}>
          <div><span>Library</span><code>npm ci{`\n`}npm test{`\n`}npm run typecheck</code></div>
          <div><span>Portfolio</span><code>cd portfolio{`\n`}npm ci{`\n`}npm run dev</code></div>
        </div>
      </section>

      <div className={styles.grid}>
        {sections.map((section) => (
          <section className={styles.card} key={section.number}>
            <div className={styles.cardHeading}>
              <span>{section.number}</span>
              <div><h2>{section.title}</h2><p>{section.description}</p></div>
            </div>
            <ul>
              {section.links.map((link) => (
                <li key={link.label}>
                  <a href={link.href}><strong>{link.label}</strong><span>{link.detail}</span><b aria-hidden="true">↗</b></a>
                </li>
              ))}
            </ul>
          </section>
        ))}
      </div>
    </main>
  );
}
